[phases.setup]
nixPkgs = [
  "python313",
  "pango",
  "cairo",
  "gdk-pixbuf",
  "gobject-introspection",
  "libffi",
  "glib",
  "shared-mime-info",
  "fontconfig",
  "freetype",
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
